[build.default]
foundry-project-root = "."
regen = false
rekompile = false
verbose = false
debug = false
o2 = true

[build.ci]
foundry-project-root = "."
regen = false
rekompile = false
verbose = false
debug = false
o2 = false

[build.local]
foundry-project-root = "."
regen = false
rekompile = false
verbose = false
debug = false
o2 = true

[show.default]
foundry-project-root = "."
verbose = false
debug = false
use-hex-encoding = false

[view-kcfg.default]
foundry-project-root = "."
use-hex-encoding = false
omit-code-cells = true
omit-interim-cells = true
omit-cost-cells = true
